name = input ("Dein Name" )
absender = ("Rene" )
print(f"Hallo {name} hier kommt dein Wöchentlicher Newsletter")
print("")
print(f"Aktienkurse steigen")
print("")
print(f"Wohnungen werden Teurer")
print(f"Grüße {absender}" )

input ("Enter")